name: Convert Markdown to Jupyter Notebooks and Push to Helper Repo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install nbformat pandoc

      - name: Convert Markdown files to Jupyter Notebooks
        run: python scripts/md_to_ipynb.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add notebooks/*.ipynb
          git commit -m "Auto-generate Jupyter notebooks from Markdown" || echo "No changes to commit"
          git push

  push_to_helper_repo:
    runs-on: ubuntu-latest
    needs: convert  # Ensures notebooks are generated before this job runs
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Clone Helper Repo
        run: |
          git clone https://github.com/UW-Madison-DataScience/AWS_helpers.git helper-repo

      - name: Copy Notebooks to Helper Repo
        run: |
          cp -r notebooks/*.ipynb helper-repo/notebooks/

      - name: Commit and Push to Helper Repo
        run: |
          cd helper-repo
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add notebooks/*.ipynb
          git commit -m "Auto-update notebooks from main repo" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.HELPER_REPO_PAT }}@github.com/UW-Madison-DataScience/AWS_helpers.git main
